### PR TITLE
Suggestions

### PR DESCRIPTION
**Pull request by JoshJancula**
Provides new methods for start/stop of foreground thread
Handles android background location permissions on install for android
Handles variable injection for iOS location usage on install, if no values are passed default value is use...
cordova plugin add @radarlabs/cordova-plugin-radar --variable NS_LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION="this is my location in usage description" --variable NS_LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION="this is my always and when in use description" --variable NS_LOCATION_ALWAYS_USAGE_DESCRIPTION="this is always"

### CODE REVIEW

**Comment by nickpatrick** [comment]
@JoshJancula Thanks! We will review, test, and release this weekend. Stay tuned.

**Comment by nickpatrick** [comment]
@JoshJancula I merged this, merged a few changes in #14 (`startForegroundThread()` renamed to `startForegroundService()`, `stopForeground()` renamed to `stopForegroundService()`, `ForegroundService` renamed to `RadarForegroundService`, notification channel renamed to `Location`, `LOCATION_USAGE_DESCRIPTION` renamed to `NS_LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION`), and released as https://github.com/radarlabs/cordova-plugin-radar/releases/tag/3.0.7.

Can you get the custom notification title and text to display? I can only get the default notification to display, perhaps because `setSmallIcon()` is not called here: https://github.com/radarlabs/cordova-plugin-radar/blob/master/src/android/src/main/java/io/radar/cordova/RadarForegroundService.java#L57 Let me know if I'm missing something. Happy to release any follow-up changes. Thanks again!

cc @brettguenther

**Comment by JoshJancula** [comment]
Thanks Nick! I had it all going just fine at one point with Brett. I had forked and fixed another plugin after Brett pointed out that this foreground business was required for radar foreground android tracking. So once it was working there I merged and brought it to radar so that other clients would not need to rely on outdated community plugins and could centralize all their radar needs to one plugin. I will go back and look at notification display though. Thanks,Josh


-------- Original Message --------
Subject: Re: [radarlabs/cordova-plugin-radar] Suggestions (#13)

**Comment by nickpatrick** [comment]
Yep, makes sense. iOS makes this easy with https://developer.apple.com/documentation/corelocation/cllocationmanager/2923541-showsbackgroundlocationindicator ("blue bar"), but Android is harder. Actually considering pulling this into the native Radar Android SDK. re: the notification, let me know what you find.

**Pull request merged**
